/**
 * Regenerates claude-usage.js from the local Claude Code transcripts.
 *
 *   node tools/build-usage.js
 *
 * Reads ~/.claude/projects/<slug>/*.jsonl, sums the per-message `usage`
 * objects by calendar day, and writes a small data file the page reads.
 * Nothing leaves this machine — the output is only day totals and counts.
 */
const fs = require("fs");
const os = require("os");
const path = require("path");

const ROOT = path.join(os.homedir(), ".claude", "projects");
const OUT = path.join(__dirname, "..", "claude-usage.js");

if (!fs.existsSync(ROOT)) {
  console.error("No Claude Code history at " + ROOT);
  process.exit(1);
}

const byDay = new Map();
let input = 0, output = 0, cacheCreate = 0, cacheRead = 0, thinking = 0;
let messages = 0, sessions = 0;
const models = new Set();

function walk(dir) {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) { walk(full); continue; }
    if (!entry.name.endsWith(".jsonl")) continue;

    sessions++;
    for (const line of fs.readFileSync(full, "utf8").split("\n")) {
      if (!line.includes('"usage"')) continue;
      let row;
      try { row = JSON.parse(line); } catch (e) { continue; }

      var usage = row && row.message && row.message.usage;
      if (!usage || !row.timestamp) continue;

      var i = usage.input_tokens || 0;
      var o = usage.output_tokens || 0;
      var cc = usage.cache_creation_input_tokens || 0;
      var cr = usage.cache_read_input_tokens || 0;

      input += i; output += o; cacheCreate += cc; cacheRead += cr;
      thinking += (usage.output_tokens_details && usage.output_tokens_details.thinking_tokens) || 0;
      messages++;
      if (row.message.model && row.message.model !== "<synthetic>") models.add(row.message.model);

      var day = row.timestamp.slice(0, 10);
      var d = byDay.get(day) || { tokens: 0, output: 0, messages: 0 };
      d.tokens += i + o + cc + cr;
      d.output += o;
      d.messages++;
      byDay.set(day, d);
    }
  }
}

walk(ROOT);

const days = [...byDay.entries()].sort(function (a, b) { return a[0].localeCompare(b[0]); });
const data = {};
days.forEach(function (entry) {
  data[entry[0]] = [entry[1].tokens, entry[1].output, entry[1].messages];
});

const payload = {
  generated: new Date().toISOString().slice(0, 10),
  totals: {
    processed: input + output + cacheCreate + cacheRead,
    output: output,
    thinking: thinking,
    cacheRead: cacheRead,
    messages: messages,
    sessions: sessions,
    activeDays: days.length,
  },
  models: [...models].sort(),
  // date -> [tokensProcessed, outputTokens, messages]
  days: data,
};

fs.writeFileSync(
  OUT,
  "/* Generated by tools/build-usage.js — do not edit by hand. */\n" +
    "window.CLAUDE_USAGE = " + JSON.stringify(payload) + ";\n"
);

console.log("Wrote " + path.relative(process.cwd(), OUT));
console.log("  " + payload.totals.processed.toLocaleString("en-US") + " tokens processed");
console.log("  " + payload.totals.output.toLocaleString("en-US") + " generated");
console.log("  " + days.length + " active days across " + sessions + " sessions");
